name: Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        run: |
          echo "${{ secrets.SSH_DEPLOY_KEY }}" > /tmp/deploy_key && chmod 600 /tmp/deploy_key
          ssh -o StrictHostKeyChecking=no -i /tmp/deploy_key root@51.15.225.121 "deploy"
          rm /tmp/deploy_key
